# Generated by Django 3.1.3 on 2020-11-18 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_auto_20201116_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='episodes.episode'),
        ),
    ]
