# Generated by Django 3.1.3 on 2020-11-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_auto_20201118_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
