# Generated by Django 3.1.2 on 2020-11-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hottakes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hottake',
            old_name='body',
            new_name='text',
        ),
    ]
