# Generated by Django 3.1.2 on 2020-11-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hottakes', '0003_hottake_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottake',
            name='image',
            field=models.ImageField(null=True, upload_to='hottakes/'),
        ),
    ]
